[package]
name = "flock-rs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "flock_rs"

[dependencies]
napi = { version = "2", features = ["napi1"] }
napi-derive = "2"
fs4 = { version = "0.12", features = ["sync"] }

[build-dependencies]
napi-build = "2"