/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Flock {
  constructor(path: string)
  lock(): Promise<void>
  unlock(): Promise<void>
  isLocked(): Promise<boolean>
}
